application: kc8zpq-dev01
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on

handlers:
- url: /update_schema
  script: update_schema_handler.app
  login: admin
  secure: always
- url: /admin
  script: admin.app
  login: admin
  secure: always
- url: .*
  script: redirector.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
