#application: kc8zpq-dev01
#version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on

handlers:
- url: /new
  script: golink.app
  login: required
  secure: always
- url: .*
  script: redirector.app

libraries:
- name: webapp2
  version: "2.5.2"
